"""user-init

Revision ID: b2256a50b708
Revises: 66174ba896f6
Create Date: 2025-05-19 02:06:51.036399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2256a50b708'
down_revision: Union[str, None] = '66174ba896f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resumes')
    op.add_column('UserProfile', sa.Column('username', sa.String(), nullable=False))
    op.add_column('UserProfile', sa.Column('password', sa.String(), nullable=False))
    op.add_column('UserProfile', sa.Column('access_token', sa.String(), nullable=False))
    op.drop_column('UserProfile', 'age')
    op.drop_column('UserProfile', 'name')
    op.drop_column('UserProfile', 'second_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('UserProfile', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('UserProfile', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('UserProfile', 'access_token')
    op.drop_column('UserProfile', 'password')
    op.drop_column('UserProfile', 'username')
    op.create_table('Resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserProfile.id'], name='Resumes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Resumes_pkey')
    )
    # ### end Alembic commands ###
