"""add foreign key in task

Revision ID: e200736970b3
Revises: 57368f3be04e
Create Date: 2025-08-21 23:19:46.445062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e200736970b3'
down_revision: Union[str, None] = '57368f3be04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Task', 'UserProfile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.drop_column('Task', 'user_id')
    # ### end Alembic commands ###
